# Generated by Django 2.2.1 on 2019-07-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=120)),
                ('deskripsi', models.TextField(max_length=500)),
                ('tanggalMulai', models.DateField()),
                ('tanggalSelesai', models.DateField()),
                ('jamMulai', models.TimeField()),
                ('jamSelesai', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=120)),
                ('alamat', models.TextField(max_length=250)),
                ('noTelepon', models.TextField(max_length=12)),
                ('pekerjaan', models.TextField(max_length=40)),
                ('instansi', models.TextField(max_length=50)),
                ('bergabungTanggal', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=120)),
                ('tanggalTerbit', models.DateField()),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifikasi_sertifikat.Kegiatan')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifikasi_sertifikat.Peserta')),
            ],
        ),
    ]
