# Generated by Django 2.2.1 on 2019-07-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifikasi_sertifikat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='alamat',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='email',
            field=models.EmailField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='instansi',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nama',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='noTelepon',
            field=models.TextField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='pekerjaan',
            field=models.TextField(blank=True, max_length=40),
        ),
    ]
